import type { Metadata } from "next";
import { archivo, berkshire_swash } from "@/lib/fonts";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import StoreProvider from "@/providers/store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${berkshire_swash.variable} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
