import "@/styles/globals.css";
import type { Metadata } from "next";
import { archivo, berkshire_swash } from "@/lib/fonts";
import { ThemeProvider } from "@/providers/theme-provider";
import { MockProvider } from "@/providers/mock-provider";
import QueryProvider from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${berkshire_swash.variable} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <MockProvider>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </QueryProvider>
        </MockProvider>
      </body>
    </html>
  );
}
